import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './style.css'
  import Header from './(components)/Header/page'
import Footer from './(components)/Footer/page'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'The Begining of ',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      <Footer/>
      </body>
    </html>
  )
}
